### ISSUE TITLE
How about a port to stylus?

### ISSUE THREAD

**Issue by prisis** [eduardoboucas/include-media#103]

**Comment by HugoGiraudel** [comment]
Feel free to do so.

**Comment by prisis** [comment]
WoW! This was fast xD

**Comment by HugoGiraudel** [comment]
I'll let @eduardoboucas say if he wants to bring it in the repo and take care of it or if he wants it to be maintained by someone else, somewhere else.

**Comment by prisis** [comment]
Okay, i will wait, than for answer from him.

**Comment by eduardoboucas** [comment]
Sorry for taking a while — crazy times over here. 

Porting the library to Stylus sounds good, but I wouldn't be able to do it. Never used Stylus. Would you be interested in having a go @prisis?

**Comment by prisis** [comment]
hi @eduardoboucas, of course :), but i need first start/finish a stylus unit test framework like true for sass. I'll keep you up to date, when i start working on the port.
https://github.com/growcss/media

**Comment by eduardoboucas** [comment]
I'll close this since it's no real issue with the library. Do keep us updated of your progress and we're happy to share it with everyone.

Thanks!
