### ISSUE TITLE
Phone Landscape and Tablet

### ISSUE THREAD

**Issue by jimbatamang** [eduardoboucas/include-media#104]
How can I write the following condition:
(> tablet) or (< tablet and landscape).

My intension is to not copy the same property when I need the same layout for Phone Landscape as in tablet.

**Comment by nathanjessen** [comment]
This is similar to open issues #102 and #132 
I don't think there is a resolution for an OR condition.

**Comment by eduardoboucas** [comment]
Moving the discussion to #102.
