### ISSUE TITLE
Error in mapping

### ISSUE THREAD

**Issue by vdms** [eduardoboucas/include-media#105]
Hi there,
I 'bower-ed' @im and when I tried to compile the project with @im, I received this error: 

Error in plugin 'gulp-ruby-sass'
Message:
    error /izzui/bower_components/include-media/dist/_include-media.scss (Line 325: $map: (("palm" "screen and (max-width: 480px)"), ("lap" "screen and (min-width: 481px) and (max-width: 1023px)"), ("lap-and-up" "screen and (min-width: 481px)"), ("portable" "screen and (max-width: 1023px)"), ("desk" "screen and (min-width: 1024px)"), ("desk-wide" "screen and (min-width: 1280px)"), ("full-hd" "screen and (min-width: 1920px)"), ("retina" "(-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi)")) is not a map for `map-has-key')

Any idea?

**Comment by HugoGiraudel** [comment]
Why compiler do you use?

**Comment by vdms** [comment]
https://github.com/sindresorhus/gulp-ruby-sass

**Comment by HugoGiraudel** [comment]
Do you still happen to have an issue with this?

**Comment by vdms** [comment]
I am working in a different team, in a different product, where include-media has not been included... yet. So, right now I can't tell if the problem still exists.

**Comment by vdms** [comment]
Maybe this issue should be closed and re-open if pertinent.
