### ISSUE TITLE
Namespacing

### ISSUE THREAD

**Issue by hctom** [eduardoboucas/include-media#107]
I just tried to implement this library while also using [Neat](http://neat.bourbon.io/). Unfortunately both libraries define ```@mixin media()```, which results in incompatibility.

Is there a chance that you might namespace all provided mixins/functions with ``ìm-```? This is already done with most components of this library, but some are not namespaced. This would make it much easier to combine your library with others.

Thanx a lot!

**Comment by prisis** [comment]
take a look on #32

**Comment by hctom** [comment]
Oh thanx, I didn't see that issue, as I only looked at open issues ;) I guess this one should work nicely.
