### ISSUE TITLE
Can't commit without having ruby + scss-lint installed ?

### ISSUE THREAD

**Issue by drazik** [eduardoboucas/include-media#111]
Hello,

I just committed some file to propose a PR, and I had some trouble because I didn't have scss-lint. I checked how to install it and found I needed ruby.

I think it's a pain to install ruby + scss-lint to be able to contribute to the project. For this reason, I just search for a nodejs alternative, but didn't found one that doesn't need ruby and scss-lint gem to be installed.

What do you think about replacing scss-lint by another tool ? Do you know another tool ? There is [stylelint](https://github.com/stylelint/stylelint/), but I don't know if it provides all the rules needed for this project.

**Comment by eduardoboucas** [comment]
I think this is one for @HugoGiraudel.

**Comment by HugoGiraudel** [comment]
Ohai. That’s fair enough. I’ll remove the pre-commit hook.

**Comment by HugoGiraudel** [comment]
Done: https://github.com/eduardoboucas/include-media/commit/40761bd6618ee1ca987f9fc3f3e4c31252ab68d4.
