### ISSUE TITLE
Sass::SyntaxError

### ISSUE THREAD

**Issue by wmantegna** [eduardoboucas/include-media#113]
I'm building a Ruby on Rails application that uses the sass-rails gem for pre-compiling.

I have tried every combination of the following file naming conventions & files where the include-media file is imported:

* _include-media.scss, include-media.scss, include-media.scss.css
* home.css.scss, application.css.scss

As soon as I add the following line of code to a .css.scss file:

    @import "include-media";

Regardless of the combination used, I get the following error:

    Sass::SyntaxError at /
    Invalid CSS after "  'phone'": expected ")", was ": 320px,"
    (in .../app/assets/stylesheets/application.css.scss:35)

Which seems to be caused by line 35 of the include-media.scss file.

**Comment by HugoGiraudel** [comment]
Which version of Sass are you using?

**Comment by wmantegna** [comment]
gemfile specifies: 'sass-rails', '~> 4.0.2'
terminal says I have versions 5.0.4, 5.0.3, 4.0.5, 4.0.2 installed

I've changed the gemfile to specify for 5.0.4 and still experienced this issue.

**Comment by HugoGiraudel** [comment]
I suspect you are using Sass 3.2 under the hood, which would explain the issue.

**Comment by wmantegna** [comment]
What version of Sass do I need?

**Comment by HugoGiraudel** [comment]
3.3+. :)

**Comment by wmantegna** [comment]
Looks like sass-rails doesn't support 3.3 yet. I tried swapping out sass-rails for the 'sass' gem (using sass v3.4), and ran into this error:

    Sass::SyntaxError at /
    File to import not found or unreadable: scaffolds.

Is there a way around this? Or am I stuck waiting for sass-rails' next release?

**Comment by HugoGiraudel** [comment]
The latest error your had is unrelated to include-media, and I believe comes from the fact you try to import an unknown file.

**Comment by noelchavez** [comment]
Hi had same issue updated my sass -v from 3.2.19 to 3.4.20 still getting an error.

**Comment by HugoGiraudel** [comment]
Is this still an issue? I cannot (and have never been able to) reproduce it on SassMeister.

**Comment by HugoGiraudel** [comment]
I’m closing.
