### ISSUE TITLE
Functions not recognised in webstorm 

### ISSUE THREAD

**Issue by David-Carty** [eduardoboucas/include-media#118]
I have the latest version of SASS compiler installed (3.4.21).  I applied "_include-media.scss" to my project.  I use Webstorm IDE (Latest version 11.0.3 and I find several functions are not recognised and as a consequence SASS fails to compile.  

      noop(), 
      get-expression-operator($condition);
      get-expression-prefix($operator);
      get-expression-value($condition, $operator);
      to-number($value);

  above functions not recognised,

Line 441 - unexpected token:

@return if($minus, -$result, $result);;   - obvious two semi-colons.

@include media(slice($conditions, 2)...) {  - invalid argument 

Shame as this appears to offer very useful functionality.

**Comment by eduardoboucas** [comment]
```
@return if($minus, -$result, $result);; - obvious two semi-colons.
```

The two aren't supposed to be there, but there's no reason why that would cause a fatal error. Neither LibSass or RubySass complain about it, as this gist shows: http://www.sassmeister.com/gist/536ad5177975f73cec28

```
@include media(slice($conditions, 2)...) { - invalid argument
```

There are no invalid arguments there.

@HugoGiraudel any ideas?

**Comment by David-Carty** [comment]
The double semi-colons are trivia, but there is a very popular IDE (Webstorm) that I, for one, cannot get the SASS to compile in.

**Comment by SimonWpt** [comment]
This seems to me a problem of strict validation. SASS is a script interpreter and process the instructions sequentially. If you  move the the functions (like noop) on top, the error messages should disappear.

**Comment by David-Carty** [comment]
Yes sir, that is correct.  But strict validation is a positive in my view.  Webstorm offer a 30 day trial if you want to see the point in question.

**Comment by SimonWpt** [comment]
I use PHPStorm and have the same problems ;)

**Comment by HugoGiraudel** [comment]
I don’t think this has anything to do with include-media in itself. Shall I close?

**Comment by eduardoboucas** [comment]
It compiles fine both on RubySass and LibSass, which are the targets we support, so I'm afraid there's not much more we can do. I'm happy for it to be closed.
