### ISSUE TITLE
Support for device only media queries

### ISSUE THREAD

**Issue by blackfalcon** [eduardoboucas/include-media#120]
While much can be done with using `max` and `min` width, there are a number of use cases where, especially for a legacy web app in transition, it would help to have `max-device` or `min-device` width media queries. 

By hacking on the `get-expression-dimension` function and updating `$dimension: "device-width";` this will address this on a global use application and that's not cool. 

It would be nice to have an option to pass into the `media` mixin. 

Maybe something like:

```
@include media("screen", "device", "<phone") {
    things ...
}
``` 

#ideas

**Comment by eduardoboucas** [comment]
I'm not a fan of that syntax, to be honest, as it's not clear to me what `"device"` means in that expression. I can't think of a better way of doing it though, which raises questions about the feasibility of this request. Any thoughts @HugoGiraudel?

**Comment by HugoGiraudel** [comment]
Hey.

I am not sure what you mean because it’s already doable:

```scss
.foo {
  @include media('device-width>large') {
    color: red;
  }
}
```

**Comment by eduardoboucas** [comment]
That is very true. My brain stopped for a minute there! 😅 

Closing.
