### ISSUE TITLE
node-sass update :: throws error "invalid unit" in breakpoint

### ISSUE THREAD

**Issue by fro35i** [eduardoboucas/include-media#125]
Due to an update of the node-module "node-sass", the include-media mixin is not working anymore.
I get the following error:
```
Invalid unit `"+600px`.
[exec] >> 39m  Line 189  Column 5  node_modules/include-media/dist/_include-media.scss
```
Last working version is node-sass@3.4.2

**Comment by HugoGiraudel** [comment]
Any chance we could have a longer stack trace or is this all you got?

**Comment by fro35i** [comment]
That's all i got.
It might be, that LibSass was updated and so node-sass has a stricter ruleset now.

**Comment by HugoGiraudel** [comment]
I can reproduce. It is caused by the + sign. Any reason you have it?

**Comment by fro35i** [comment]
I've no idea, I am not writing any +-signs, I need to debug more, thanks.

**Comment by HugoGiraudel** [comment]
Actually I fixed it in a PR. Waiting for @eduardoboucas to review.
