### ISSUE TITLE
CodeKit quit unexpectedly

### ISSUE THREAD

**Issue by mmjaeger** [eduardoboucas/include-media#127]
Hello
as soon as I add "$im-media-support: true;" to the settings file or include the provided _config.scss file, CodeKit crashes - any idea what's going on?

Thanks

**Comment by HugoGiraudel** [comment]
Any more issue on what does your code look like, what Sass version you use, what CodeKit version you use…

**Comment by mmjaeger** [comment]
using the latest CodeKit version (2.8) and using libsass compiler - if I
don't enable libsass, it works as well. when including the
_include_media.scss file instead of _media.scss it works as well regardless
whether libsass is enabled or not.

On Wed, May 11, 2016 at 12:34 AM, Hugo Giraudel <notifications@github.com>
wrote:

> Any more issue on what does your code look like, what Sass version you
> use, what CodeKit version you use…
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/eduardoboucas/include-media/issues/127#issuecomment-218383993>
>



-- 
Marco M. Jaeger
http://net4visions.com

**Comment by eduardoboucas** [comment]
Is there any particular reason why you want to include `_media.scss` instead of the distribution file (`_include-media.scss`)?

**Comment by mmjaeger** [comment]
no, I guess there's no reason to include _media.scss instead of
_include-media.scss - I was still wondering though why it causes the error
with CodeKit.

On Thu, May 12, 2016 at 2:50 AM, Eduardo Bouças <notifications@github.com>
wrote:

> Is there any particular reason why you want to include _media.scss
> instead of the distribution file (_include-media.scss)?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/eduardoboucas/include-media/issues/127#issuecomment-218710879>
>



-- 
Marco M. Jaeger
http://net4visions.com

**Comment by eduardoboucas** [comment]
You should be using the distribution file, particularly when relying on anything other than raw LibSass/RubySass to compile. We don't know what CodeKit is doing internally.

Closing.
