### ISSUE TITLE
`dppx` detection

### ISSUE THREAD

**Issue by raphaelgoetter** [eduardoboucas/include-media#128]
Hello,

What about adding the `dppx` unit in the "retina" detection rules (such as `'retina2x': '(-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi)'`) ?

**Comment by HugoGiraudel** [comment]
Ping @eduardoboucas.

**Comment by eduardoboucas** [comment]
To be clear, you're talking about changing the [default definition](https://github.com/eduardoboucas/include-media/blob/master/src/_config.scss#L38) of the `retina2x` expression, right? You can tailor those definitions to your project by re-declaring `$media-expressions`.

If you think we should change the default definition, feel free to send a PR. I haven't used `dppx` units myself, to be honest, but even though the default definitions are just a guideline, we need to be careful with breaking changes for people that currently rely on them.

**Comment by raphaelgoetter** [comment]
Well, you're right, it's easy to override the default definition.

However, proposing `dppx` as default would be a wise idea as it is meant for that. You could still add fallback with `dpi` if you want : 'retina2x': '(min-resolution: 192dpi), (min-resolution: 2dppx)'

**Comment by eduardoboucas** [comment]
Added by #129.
