### ISSUE TITLE
How can I use OR expression in breakpoints?

### ISSUE THREAD

**Issue by jdjuan** [eduardoboucas/include-media#132]
Hello Include-media Team!,

I am just wondering how can I achieve something like this: 

`@include media("<=900px OR height<700px"){ ... }`

The following way works like an AND: but I need an OR

`@include media("<=900px",  "height<700px"){ ... }`

Today I use 2 different `@include`, and it works. But I couldn't figure out how to achieve the above.

**Comment by HugoGiraudel** [comment]
It’s not possible with include-media. Sorry! :)

**Comment by HugoGiraudel** [comment]
Possible duplicate of #102.

**Comment by eduardoboucas** [comment]
Moving the discussion to #102.
