### ISSUE TITLE
Error:

### ISSUE THREAD

**Issue by mmjaeger** [eduardoboucas/include-media#136]
I got the following code in a mixin:

```scss
@inlude media('>sm') {
  @content;
}
        
@media (min-width: #{$width}) {
  @content;
}
```

I'm getting the following error: You may not @extend an outer selector from within @media - this only happens when using the include-media mixins - the native @media query works - any way around this?

**Comment by eduardoboucas** [comment]
Is this what you're trying to achieve? http://www.sassmeister.com/gist/39225a1a1322e916027e1939a825f177

**Comment by HugoGiraudel** [comment]
Include-media does not use `@extend` at all, and does nothing more than outputting media blocks. I hardly thing this issue comes from our side. If you can reproduce it with a reduced test case, please re-open.
