### ISSUE TITLE
no error on unitless int

### ISSUE THREAD

**Issue by robsonsobral** [eduardoboucas/include-media#147]
Hi, Eduardo! I'm using include-media for the first time on a real job and loving it. Thank you!

Some of my breakpoints are called `1col`, `2col`, `3col` and so on... By mistake, I typed `@include media('>=4')`. Shouldn't this return an error?

`@include media('>=X')` returns `Invalid unit`, if there's no `X` breakpoint.

Thank you for your attention.

**Comment by tzi** [comment]
I don't know why, but unitless values are clearly authorized in the code.
Allowed by this commit: https://github.com/eduardoboucas/include-media/commit/ae6da96b7ef81efb7c891b1031bc4da0998d73b0

/ping @HugoGiraudel

**Comment by robsonsobral** [comment]
It looks like this map is only related to "jumps" between a `<` and a `>=`, because we don't have a float pixel. Is the commit intended to prevent a bug in a case of a unitless media query? I think so.

uniless media queries:

- aspect-ratio;
- orientation;
- overflow-block
- overflow-inline;
- scan;
- update;

Aaaaaaaaaaaaaaaaaaaaaaaand:

- [color](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/color);
- [color-index](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/color-index).

So, it isn't a bug, after all.

**Comment by robsonsobral** [comment]
All [@media](https://developer.mozilla.org/en-US/docs/Web/CSS/@media), if you want to take a look, @tzi .

**Comment by HugoGiraudel** [comment]
Unitless values are authorized for things like aspect-ratio.
