### ISSUE TITLE
Distribute this library via bower

### ISSUE THREAD

**Issue by mslemeri** [eduardoboucas/include-media#15]
I just finished reading your article on CSS-Tricks and think this would be a perfect candidate for distribution via Bower. Here are a few other (popular) repos I found on Bower that have the same goal, so we can probably use the same keywords in the `bower.json` file for maximum visibility on Bower:

* https://github.com/lolmaus/breakpoint-slicer
* https://github.com/sass-mq/sass-mq
* https://github.com/paranoida/sass-mediaqueries

It's a great library and I think it deserves the exposure!

**Comment by eduardoboucas** [comment]
Sounds great! I'm not too familiar with the process required to distribute something via Bower, to be honest. Would you be able to help?

**Comment by mslemeri** [comment]
Sure, no problem! I can fork and add the required file (bower.json) to the project root and have you look it over in a PR. We would probably wanna update the README as well to tell folks they can install via bower.

**Comment by eduardoboucas** [comment]
I've done that already. Just created another branch. Could you take a look?

How would people then install the package? I know they can just run `bower install include-media`, which creates a directory inside `bower_components`, but would you then import the file into your Sass using that path?

**Comment by mslemeri** [comment]
Only thing that I'm not sure about is the [`moduleType` key](https://github.com/eduardoboucas/include-media/blob/add-bower/bower.json#L10-L12). That might've been in an older version of the [bower.json spec](https://github.com/bower/bower.json-spec), but it's not there now. Other than that, I think it looks good.

To answer your second question, yes, that would be the process for importing the file into their own code.

**Comment by eduardoboucas** [comment]
I used `bower init` to create the manifest file, but maybe it's outdated.

I'll get this merged and update the README. Thanks for your help man!

**Comment by mslemeri** [comment]
Oh okay, my apologies. It probably doesn't make much difference. The important things are the description, name, and keywords.

**Comment by eduardoboucas** [comment]
Fixed in [#17](https://github.com/eduardoboucas/include-media/pull/17).

Thanks @mslemeri!
