### ISSUE TITLE
Update linting to conform to latest Sass Guidelines

### ISSUE THREAD

**Issue by jackmcpickle** [eduardoboucas/include-media#156]
@eduardoboucas have you thought about adding a linter to the test. Could help with issues around class formating and the like. I use sass-lint, but I think they are all the similar.

**Comment by eduardoboucas** [comment]
I'm in the process of integrating Travis, so this might be a good time to add linting to the process. Are you able to help with that?

**Comment by eduardoboucas** [comment]
Well, actually we do have linting: https://github.com/eduardoboucas/include-media/blob/master/.scss-lint.yml (I'm clearly still half asleep). 😴 

I should be able to just add this to the test suite and integrate with Trevis.

**Comment by HugoGiraudel** [comment]
We should sync this linter up to the latest version (Sass Guidelines).

**Comment by Nirazul** [comment]
A thing to note about `scss-lint`: You need to have the gem installed, which (as far as I've seen it) is not described anywhere as a prerequisite.

**Comment by eduardoboucas** [comment]
A pure Node.js solution would be better, especially as even Sass itself is moving away from Ruby. Could we use [this one](https://github.com/sasstools/sass-lint) instead?

**Comment by robsonsobral** [comment]
SASS-lint isn't (yet) good enough to replace SCSS-lint. Too many options missing and too many bugs. Specially with indentation.

**Comment by jackmcpickle** [comment]
I've used sass-lint for the last year or so. Havent seen too many problems. Most of the issue I've had are with integration with the editors..

**Comment by jackmcpickle** [comment]
Either way - will put something together shortly.

**Comment by Nirazul** [comment]
When it comes to linting, [stylelint](http://stylelint.io/) is very mature and works well, but focuses on css. However, there's [a scss plugin](https://github.com/kristerkari/stylelint-scss) that covers special scss syntax.

**Comment by eduardoboucas** [comment]
Closed via #158.
