### ISSUE TITLE
Support for min-height

### ISSUE THREAD

**Issue by mattberridge** [eduardoboucas/include-media#16]
Feature request: any plans to support `min-height` queries?

**Comment by eduardoboucas** [comment]
We can do it, but I think the challenge is how to accomplish it and still maintain a nice and simple syntax at the same time.

Can you give an example of how you'd like the syntax to be for a `min-height` media query? 

I really want to keep the breakpoint declaration simple, so I'd try to avoid having something like:

``` sass
$breakpoints: (phone: (width: 123px, height: 321px), tablet: (width: 123px, height: 321px), desktop: (width: 123px, height: 321px));
```

I think it becomes too complex.

You could keep the regular declaration of breakpoints and just say that those values are actually heights and not widths, but then you'd lose the ability to use `min-width` expressions at all, which is not ideal.

Worth thinking about though, thanks for the request!

**Comment by KrisOlszewski** [comment]
What about 2 separate lists for horizontal and vertical breakpoints? Check if key exists in horizontal list, and if not, check if it exists in vertical list.

Something like this:

```sass
$breakpoints--horizontal: (
  phone: 320px,
  tablet: 750px
);

$breakpoints--vertical: (
  landscape: 600px,
  portrait: 900px
);

.selector {
  @include media(">phone", "<=tablet", ">landsape", "<=portrait") {
    width: 100%;
  }
}
```

**Comment by eduardoboucas** [comment]
That solution seems too complex for the benefits it brings. I'd rather add `(orientation : landscape)` and `(orientation : portrait)` to `$media-expressions` so you could do something like:

``` sass
@include media(">phone", "<=tablet", "landscape") {
    // Stuff
}
```

The syntax seems more natural than `">landscape", "<=portrait"` and it's detecting orientation in the correct way. 

I honestly can't see a typical scenario where you would need to create a media query using `min-height`, but I might be wrong.

**Comment by KrisOlszewski** [comment]
It's not really about orientation for device. It would be great to have an ability to add constrains between width and height to accommodate odd-sized devices.

It would come extremely handy when you have to code design with sections that cover full viewport with centered content (vertically and horizontally).

I see your point tho, this enhancement would only be useful for edge cases.

**Comment by CREEATION** [comment]
There [are](http://trentwalton.com/2012/01/11/vertical-media-queries-wide-sites/#comment-23589) [enough](http://trentwalton.com/2012/01/11/vertical-media-queries-wide-sites/) [reasons](https://boagworld.com/dev/are-media-queries-the-answer-to-the-fold/) to support min-height, actually.
:+1: for `min-height` support!

**Comment by KrisOlszewski** [comment]
This is what I'm currently using for managing Media Queries in Sass: https://github.com/KrisOlszewski/snippets/tree/master/sass/media-queries It's nothing fancy and way less elaborate than `include-media`, but it accommodates horizontal and vertical cases.

Sass is smart enough to recognize nested Media Queries and combines them in output.

**Comment by pauleustice** [comment]
Firstly, thanks for a great plugin @eduardoboucas! There are definitely use cases for vertical viewport sizes (I came across one today). As adoption for vh units increases, I think this need could become more prevalent.

How about an *optional* prefix for arguments that can indicate vertical (i.e. height-based) queries? Any unprefixed values would be assumed to refer to width-based queries. Something like:

```
$breakpoints: (
  phone: 320px,
  tablet: 750px
);

.selector {
  @include media(">h:phone", "<=h:tablet") {
    ...
  }
}
```

Would that work?

**Comment by eduardoboucas** [comment]
Thanks @pauleustice!

I have to say that I'm not a huge fan of the syntax, as it wouldn't be immediately clear what the expression means, which to me is one of the most appealing things about this mixin. 
However, I do appreciate the need of adding support for `min-height` media queries and I don't think it's fair to discard that just to keep the syntax pretty. 

I'll have a play with it and see what the best implementation could be. If anyone has any suggestions, feel free to add to this discussion or submit a PR.

**Comment by eduardoboucas** [comment]
Ok, here's [my attempt](https://github.com/eduardoboucas/include-media/commit/d9866e5f4961c99ca856cebbbb324a8c53f20130). It followed @pauleustice's idea, but it's using a slightly different syntax.

```sass
@include media('height>1100px', 'height<=desktop') {
    // ...
}
```

For consistency's sake it now accepts the `width` prefix as well, even though it's inferred automatically if not present.

```sass
@include media('width>=500px') {
    // ...
}
```

Here's a [Sassmeister gist](http://sassmeister.com/gist/5192409e14efd3349376) with the implementation in case you want to play with it.

The problem I can think of at the moment is that the breakpoint declaration is independent of whether it's a width or a height value. For example, using `width>=breakpointA` and `height>=breakpointA` will result in a `min-width` and a `min-height` media queries with the exact same value, which might not be ideal.

Thoughts?

**Comment by pauleustice** [comment]
Personally I don't see that as a problem - quite the opposite in fact. Breakpoints should just be mapped values independent of viewport axis, right?

**Comment by eduardoboucas** [comment]
I don't see it as a huge problem, to be honest. I just think that the expression `@include media('>=phone') {}` suggest that it's a media query for viewports wider than a phone's viewport width and that `@include media('height>=phone') {}` suggests a media query for viewports higher than a phone's viewport **height**.

But it should be fine as long as it's well documented.

@mattberridge @KrisOlszewski @CREEATION are you happy with this approach?

Thanks all!

**Comment by joseluis** [comment]
I like the new syntax very much.

I think I know what @eduardoboucas means about the breakpoints names. It's about clarity, symmetry and simplicity. In that regard I want to propose the only improvement that makes sense to me:

1. Now we have a generic `$breakpoints` map. We keep that one, which can still be used in the same way as before. Even with the new syntax for heights.
1. But we can also define `$breakpoints-width` and `$breakpoints-height`, which are ONLY used for widths or for heights, specifically.
1. The key is searched first on the appropriate *specific* breakpoint map. Only when it's not found there it's searched on the generic `$breakpoints` map.

This way, we can mantain full backwards compatibility, and for heavy widht / height usage we can have clarity and simplicity:

```
$breakpoints-width: (phone: 480px, tablet: 1024px, desktop: 1280px);
$breakpoints-height: (phone: 320px, tablet: 768px, desktop: 1024px);

@include media( "width>phone", "width<=tablet" ) {
width: 50%;
}
@include media( "height>phone", "height<=desktop" ) {
height: 50%;
}
```

The only question whether this is better and less confusing than using the old system like this:
```
$breakpoints: (phone: 480px, tablet: 1024px, desktop: 1280px,
                    phone-height: 320px, tablet-height: 768px, desktop-height: 1024px);

@include media( "height>phone-height", "height<=desktop-height" ) {
height: 50%;
}
```

**Comment by KrisOlszewski** [comment]
All sounds great. Determining semantic names for breakpoints across horizontal and vertical axis would create biggest obstacles. If you set `phone`, `tablet`, `desktop` for height it won't make much sense, mainly because you could have MacBook Air 11" which has exact same height as iPad in landscape view. Same goes for any phone in portrait view vs tablet in landscape view.

The main objective is to create constrain based media queries. In example, I want to tell me Sass pre-process to magically create a media query that will only execute if viewport is below/between/above vertical and/or horizontal axis.

This would work well:

```sass
@include media('>=1200px', 'height<500px') {}
```
or
```sass
@include media('>=large', 'height<small') {}
```
with
```sass
@breakpoints: (
  "width": (
    // ...
    "large": "1200px"
  ),
  "height": (
    "small": "500px",
    // ...
  )
);
```

@eduardoboucas I think you're on a great path. Looking forward to see it in action! Thanks for adding this feature.

**Comment by stacyk** [comment]
Yay! My only wishlist item was adding support to target height. I am super happy to see this thread. This is a big +1 for me :+1:

**Comment by eduardoboucas** [comment]
I like the idea of adding the ability to use existing breakpoints to build `min-height` expressions (so basically what I proposed in this thread on the 4th of April).

@KrisOlszewski's approach seems a bit more complex and I don't really like the idea of separating the `$breakpoints` map into width and height breakpoints. I think there's a huge risk of losing the simplicity of the library.

@stacyk which flavour are you more interested in?

**Comment by stacyk** [comment]
I think the least amount of typing while coding the best. And I know I target height WAY less frequently than width so something like:

@include media('>=phone', 'height<=whatever-variable-name') {}

makes a great deal of sense to me. By default, width is just assumed. Then being able to declare a variable for whichever height value (or write one is but I like to variable-ize everything) works if you want to add a height parameter.

Uh oh, tornado sirens going off. Gotta go check that out.

**Comment by eduardoboucas** [comment]
Yes, that's precisely what I suggested. I think we're getting closer to implementing this.

Thanks y'all!
