### ISSUE TITLE
Update documentation and site with yarn

### ISSUE THREAD

**Issue by eduardoboucas** [eduardoboucas/include-media#160]
We need to update the installation instructions to include Yarn, as per #159.

Files:

- README: https://github.com/eduardoboucas/include-media/blob/master/README.md
- Site: https://github.com/eduardoboucas/include-media/blob/gh-pages/index.html

@jackmcpickle will it simply be `yarn add include-media`?

**Comment by jackmcpickle** [comment]
Correct. But remember it fetches packages from the npm registry too.
