### ISSUE TITLE
"Critical dependency: the request of a dependency is an expression" warning when compiling with webpack

### ISSUE THREAD

**Issue by MatthewPikar** [eduardoboucas/include-media#162]
When including include-media within a webpack bundle, the following warning comes up: 
```
WARNING in ./~/include-media/index.js
4:17-46 Critical dependency: the request of a dependency is an expression
```

I am able to make it go away by making the required path static:
```
//var entryPoint = require.resolve(package.name);
//var distPath = path.join(path.dirname(entryPoint), 'dist');
var distPath = require('./dist/_include-media.scss');
```

**Comment by jackmcpickle** [comment]
@MatthewPikar have you tried using an alias too?

**Comment by jackmcpickle** [comment]
Looking back at https://github.com/eduardoboucas/include-media/pull/110 which was where the index.js files was added - It doesn't quite make sense why it was added - just to make importing into include-media sass files easier. I always add `includePaths: 'node_modules'` to my sass tasks. I believe undoing this PR would help with webpack requiring it. But an alias should do the trick too.

**Comment by MatthewPikar** [comment]
I tried adding includePaths, like  you suggested, but the error persists.  I'll try aliasing, but it feels wonky to me to do that for external libraries like this, unless I don't follow what you are recommending to alias.

Thank you

**Comment by MatthewPikar** [comment]
To be more specific, this is the includePaths config I used:
```
loader: 'sass',
options: {
  includePaths: [path.resolve(__dirname, '../', 'node_modules')]
}
```
It resolves to the correct path, but maybe I'm doing something wrong there.  I'll look through sass loader docs some more.

Package versions:
```
    "webpack": "^2.2.1",
    "include-media": "^1.4.9",
    "sass-loader": "^6.0.2"
```

**Comment by jackmcpickle** [comment]
@MatthewPikar How are you including it in your code?

Because it will continue to have this issue if you just `require('include-media')` as that will grab the index.js file. try requiring `'include-media/dist/include-media'` or create an alias that points to this file.

**Comment by MatthewPikar** [comment]
I've been using @import 'node_modules/include-media/dist/_include-media.scss' the whole time.  I'll make the alias.

**Comment by MatthewPikar** [comment]
I've aliased the path and the error no longer appears.  

Aliasing into packages is a bit of a hack though.  I could be doing something wrong, when using includePaths, and I definitely plan on getting back into it to get this right.  That being said, having includePaths configured to use include-media feels awkward.  It's great as an option, but feels like it should work the standard way too.  Then again, maybe this just stems from the peculiarities of my specific webpack setup.

Thank you for the help.  Cheers.
