### ISSUE TITLE
IncludeMedia for Sass V3.1

### ISSUE THREAD

**Issue by ConduciveMammal** [eduardoboucas/include-media#163]
I've been using IM for a while now and found it immensely helpful, so firstly, thank you for that.

Now, I'm trying to use in Shopify's new Slate CLI which compiles Sass on the server. My problem now is for some ridiculous reason, their brand new compiler only supports up to Sass V3.1, whereas IM is built for 3.4.
I'm wondering if you have any old gists that were built for 3.1?

**Comment by eduardoboucas** [comment]
3.1 is quite old. From a quick look at [the change log](http://sass-lang.com/documentation/file.SASS_CHANGELOG.html#320_10_august_2012), version 3.2 introduced `@content`, which include-media requires.

You can easily try all the various versions from the [releases page](https://github.com/eduardoboucas/include-media/releases), but I'm afraid you won't be able to find one that works with such an old version of Sass.
