### ISSUE TITLE
Mix media selectors: AND and OR

### ISSUE THREAD

**Issue by NikFlip** [eduardoboucas/include-media#165]
Hey guys,
I'm using now your framework for a long time and everything worked fine for me.
But now I've got a problem. I would like to get a media-query that looks like this:

```css
@media (max-width: 500px), (max-width: 1000px) and (min-width: 769px) { ... }
```

I imaged something like this:

```sass
@include media(('<=500px), ('<=1000px', '>tablet')) { ... }
```
Is there any solution? 
My workaround looks like this:

```sass
@include media('<=1000px', '>tablet') { ... }
@include media('<=500px) { same code as media query before... }
```
Thank's in advice
Nik

**Comment by jackmcpickle** [comment]
@NikFlip there has been many discussions around OR queries. See https://github.com/eduardoboucas/include-media/issues/102 for reference as a place to start.

**Comment by NikFlip** [comment]
Hi @jackmcpickle. Thank you. I'll close this issue now. :)
