### ISSUE TITLE
"Or" conditional

### ISSUE THREAD

**Issue by nunospot** [eduardoboucas/include-media#166]
Hello,

I have a question. It's possibel to make a media query with a "or" conditional?

For example:

`@include media('>tablet-landscape', 'retina2x') `

But in this case I want this query works on both devices higher than tablet-landscape **OR** retina2x screens.

Thank you and keep the good work.

**Comment by jackmcpickle** [comment]
Hi @nunospot See issue https://github.com/eduardoboucas/include-media/issues/102 
There is now a https://github.com/nirazul/include-media-or

**Comment by eduardoboucas** [comment]
^ what @jackmcpickle said 😊

Closing.
