### ISSUE TITLE
Add support for sass-module-importer?

### ISSUE THREAD

**Issue by rfgamaral** [eduardoboucas/include-media#167]
[`sass-module-importer`](https://github.com/lucasmotta/sass-module-importer) requires the following to work:

> Assuming that the external library you are installing fits under one of those categories:
> 
> 1. Set a SCSS/Sass/CSS file on the "main" field of their package.json/bower.json
> 2. Set a SCSS/Sass/CSS file on the "style" field of their package.json/bower.json
> 3. Have a `index.css` file on the root of their module
> 

But `include-media` currently supports neither.

What do you think of adding `"style": "dist/_include-media.scss"` to `package.json`? Or perhaps replacing the `main` property instead would make more sense? Thoughts?

P.S: I can open a pull request for this if needed. Just need to know if you're OK with it and which version would you prefer to be implemented.

**Comment by eduardoboucas** [comment]
Thanks for that! I think that adding `style` would be a safer choice, as changing `main` could be a breaking change for other systems?

@HugoGiraudel do you see any problems with this?

**Comment by HugoGiraudel** [comment]
I think it should be fine.

**Comment by eduardoboucas** [comment]
Great, thanks!

@rfgamaral Would you mind opening a PR adding the `style` property then? (Also, sorry about the delayed response – just noticed the issue has been sitting here for a while. 😳)
