### ISSUE TITLE
media query compiles before the block if I use hovers

### ISSUE THREAD

**Issue by skylite21** [eduardoboucas/include-media#168]
I have the following block which is totally fine:

```
header {
  @include media('>phone', '<=tablet') {
    flex-direction: column;
  }
  flex-direction: row;
}
```

because it compiles to:

```
header {
  flex-direction: row;
}
@media (min-width: 321px) and (max-width: 768px) {
  header {
    flex-direction: column;
  }
}
```
And its fine because the media query goes after the header rule. 

But in this example:

```
.search {
  @include media('>phone', '<=tablet') {
    &:hover {
      width: 190px;
    }
  }
  &:hover {
    width: 250px;
  }
}
```

This compiles to:

```
@media (min-width: 321px) and (max-width: 768px) {
  .search:hover {
    width: 190px;
  }
}

.search:hover {
  width: 250px;
}

```
So this does not wok properly because this time the .search:hover rule overwrites the media query.
The only way I could solve this is by moving te include part at the end of the .search block, but then I get the "Mixins should come before declarations (mixins-before-declarations)" Warning.

What would be the proper way to do this? ( If i loose nesting  and just put the media queries at the end, sure that works but why do I have to do that? )

Thanks for your help!

**Comment by Nirazul** [comment]
@skylite21 
`Mixins should come before declarations (mixins-before-declarations)` stems from a linting plugin and not from `include-media`. You should alter its rules.

There's actually nothing this plugin can do about the location it is writing the media rules. That's sass compiler logic.

**Comment by skylite21** [comment]
My problem is the linter rule altering. Why using the linter if I ignore its warnings? Assuming they meant to do the right thing :(

**Comment by Nirazul** [comment]
I see that this rule can generally be helpful, but when you need to alter perfectly fine code to resolve warnings, I find it hard to see the benefit of it :/

I'm using stylelint. There you can independently decide on the position of blockless rules and those with blocks.

You could also wrap the block in a meaningless media query, so you're allowed to position it before it. But I really don't see the advantage as you're working around rules instead of using them to your advantage :/

```scss
@media screen {
  .search:hover {
    width: 250px;
  }
}
@media (min-width: 321px) and (max-width: 768px) {
  .search:hover {
    width: 190px;
  }
}
```

**Comment by robsonsobral** [comment]
Mixins with content should always be set after the declarations. Not all lints accept that. But I think you can set exceptions on your lint.

**Comment by skylite21** [comment]
Ok. For anyone who finds this, this is the way to ignore it for this line only: 

```
.search {
  &:hover {
    width: 250px;
  }
  @include media('>phone', '<=tablet') { // sass-lint:disable-line mixins-before-declarations
    &:hover {
      width: 190px;
    }
  }
}
```

**Comment by robsonsobral** [comment]
Even better, @skylite21 :

```yaml
  mixins-before-declarations:
    - 1
    - exclude: ['breakpoint', 'media', 'mq']
```

On the `sass-lint.yaml`.
