### ISSUE TITLE
Concept ported to Angular

### ISSUE THREAD

**Issue by mystrdat** [eduardoboucas/include-media#169]
Hi guys! After working with Angular 4 recently, we found that the available 3rd party media query modules are rather poor quality and since I've always enjoyed the methodology you came up with on this project, we made it a core feature in our new open source module. While there are some differences in our implementation, I was thinking you might might enjoy knowing about its existence anyway: https://github.com/salsita/ng2-if-media

Thanks and have a great 2018!

**Comment by HugoGiraudel** [comment]
That’s great, thank you! :)
