### ISSUE TITLE
No operator found in `phone`

### ISSUE THREAD

**Issue by winchendonsprings** [eduardoboucas/include-media#176]
I've imported the _include-media.scss and upon building my my scss file with node-sass the error i receive is 

> {
>   "status": 1,
>   "file": "/my-dir/scss/_include-media.scss",
>   "line": 190,
>   "column": 5,
>   "message": "No operator found in `phone`.",
>   "formatted": "Error: No operator found in `phone`.\n        on line 190 of _include-media.scss, in function `im-log`\n        from line 278 of _include-media.scss, in function `get-expression-operator`\n        from line 368 of _include-media.scss, in function `parse-expression`\n        from line 562 of _include-media.scss, in mixin `media`\n        from line 45 of custom.scss\n>>     @error $message;\n\n   ----^\n"
> }

Any idea why it won't build? 

Maybe I need a more basic 'how to setup' than what's documented here - https://include-media.com/documentation/

I'd recommend documenting exactly how to import the _include-meda.scss file and exactly where and in what file to declare the $breakpoints:()

When I import the file and use the first code snippet from - https://include-media.com/#features I receive the compile error above

Thanks

**Comment by jackmcpickle** [comment]
@stephenbe I need more info on how you are importing into you project before I can help. There are default breakpoints defined in include-media so if you have manually grabbed the file and are trying to use then there maybe an issue that is unique to your case. 

Normally I install include-media via `npm install include-media` then add node_modules as an include_path on the sass options in my gulp script. See here. https://github.com/sass/node-sass#includepaths - then you can import into you project like. `@import 'include-media/dist/include-media'`.

**Comment by ArialBlack** [comment]
> I've imported the _include-media.scss and upon building my my scss file with node-sass the error i receive is
> 
> > {
> > "status": 1,
> > "file": "/my-dir/scss/_include-media.scss",
> > "line": 190,
> > "column": 5,
> > "message": "No operator found in `phone`.",
> > "formatted": "Error: No operator found in `phone`.\n        on line 190 of _include-media.scss, in function `im-log`\n        from line 278 of _include-media.scss, in function `get-expression-operator`\n        from line 368 of _include-media.scss, in function `parse-expression`\n        from line 562 of _include-media.scss, in mixin `media`\n        from line 45 of custom.scss\n>>     @error $message;\n\n   ----^\n"
> > }
> 
> Any idea why it won't build?
> 
> Maybe I need a more basic 'how to setup' than what's documented here - https://include-media.com/documentation/
> 
> I'd recommend documenting exactly how to import the _include-meda.scss file and exactly where and in what file to declare the $breakpoints:()
> 
> When I import the file and use the first code snippet from - https://include-media.com/#features I receive the compile error above
> 
> Thanks

maybe you just wrote:
 @include media('phone') {}
I received the same error. Try to add '<' or '>'
Like  @include media('>phone') {}

**Comment by HugoGiraudel** [comment]
Is this still an issue?

**Comment by caberg** [comment]
happen to me too when using breakpoint label, but no error if im using unit value
ex: @include media('<=991px') {

**Comment by caberg** [comment]
its now fix ^_^ , it seems both https://github.com/HugoGiraudel/sass-boilerplate and and **include media** have same variable and it's clash when using breakpoints label.

here's the code in sass boilerplate in _variables.scss
` $breakpoints: (
 	'small': 320px,
 	'medium': 768px,
 	'large': 1024px,
 ) !default;`

**Comment by jackmcpickle** [comment]
Good to know. Thanks @caberg
