### ISSUE TITLE
Error: property "​" must be followed by a ':'

### ISSUE THREAD

**Issue by electricarts** [eduardoboucas/include-media#178]
I don't know what i'm doing wrong, but when writing Sass like

`.portfolio-start h2.elementor-portfolio-item__title {
	@include media(">phone", "<=tablet") {
    font-size: 1.2em !important;
		margin-bottom: 1.5em;
	}​
}`

i get this error: 

`Libsass: Error: property "​" must be followed by a ':'
        on line 116 of Users/mario/Sites/hellmann-salami.test/wp-content/themes/hellmann/sass/style.scss`

Line 116 is the first closing bracket (after the margin-bottom).

**Comment by jackmcpickle** [comment]
You have a bad invisible character between the last 2 `} }` usually happens from a bad copy paste or miss type. copy into https://www.sassmeister.com/ and see.

**Comment by electricarts** [comment]
Holy crap. I would never have thought of that. Thank you very much for your help!
