### ISSUE TITLE
_include-media.scss:7:17: Unclosed bracket

### ISSUE THREAD

**Issue by rockmanvnx6** [eduardoboucas/include-media#179]
Hello,

I ran into this error recently, currently using:
- "include-media": "^1.4.9",
- "node-sass": "^4.12.0",

This is how I implemented:
```scss
@import url('~include-media/dist/_include-media.scss');
```

This is the screenshot:
![image](https://user-images.githubusercontent.com/16440123/66890254-308b2580-f031-11e9-9df5-13cfeefa6b30.png)

**Comment by Toddses** [comment]
This is an issue with your build process. `You tried to parse SCSS with the standard CSS parser`

**Comment by rockmanvnx6** [comment]
I see, thanks, It's so weird that I didn't have to configure anything before.
