### ISSUE TITLE
Or statement

### ISSUE THREAD

**Issue by grloch** [eduardoboucas/include-media#185]
Hi guys!

It is possible usa a "OR" statement? Something like: `@include media(">=phone", "or >=desktop"){...}`

Compiling to: `@media (min-width: 123456px), (min-width: 456789px){...}`

I tried look on documentation, but didn't found anything related to this.

**Comment by jackmcpickle** [comment]
Hi @grloch See issue #102
There is now a https://github.com/nirazul/include-media-or
