### ISSUE TITLE
[Documentation] Website down? https://include-media.com/

### ISSUE THREAD

**Issue by nlxdodge** [eduardoboucas/include-media#186]
The website https://include-media.com/ is down for me and other down checkers online. But this website also hosts most of the documentation.

Could the owner take a look at this?

Thanks in advance.

**Comment by eduardoboucas** [comment]
Hi! I'm not planning on renewing the include-media.com domain, because I can't really justify the cost. The documentation is now available at http://eduardoboucas.github.io/include-media/.

Any suggestions on where this information should be updated? (cc @jackmcpickle)

**Comment by jackmcpickle** [comment]
@eduardoboucas looks like readme needs an update too as the links will be broken.

**Comment by jackmcpickle** [comment]
https://github.com/eduardoboucas/include-media/pull/188

**Comment by lalli-flores** [comment]
The [Contribution guidelines](https://github.com/eduardoboucas/include-media/blob/master/CONTRIBUTING.md) should probably be updated with along that PR

**Comment by CharlesKumar** [comment]
Hi @eduardoboucas, 

An update the home page url from [include-media.com](include-media.com) to [http://eduardoboucas.github.io/include-media/]( http://eduardoboucas.github.io/include-media/) in the [npm project page](https://www.npmjs.com/package/include-media) would be cool.
