### ISSUE TITLE
Compiling error in IDE's with media(slice($conditions, 2)...) - possible fix

### ISSUE THREAD

**Issue by axelBrauneder** [eduardoboucas/include-media#189]
In the last mixin at the bottom of the file, there is always a compiling error. It seems like that's only the case on most IDE's, not when compiling directly. See image for notice:

<img width="674" alt="include-media-sass-error" src="https://user-images.githubusercontent.com/15448656/76621235-31b47600-652f-11ea-99b2-d6a637362d66.png">

This is what seems to be causing the issue:
`@include media(slice($conditions, 2)...) {
      @content;
    }`

So my suggestion would be to change it to the following:
`$sliced-conditions: slice($conditions, 2);`
`@include media($sliced-conditions...) {
      @content;
    }`

<img width="667" alt="include-media-sass-no-errors" src="https://user-images.githubusercontent.com/15448656/76621788-84daf880-6530-11ea-9dc9-2e3d9cef2153.png">

That seems to not be throwing any errors, and I haven't had any issues with it yet. Could that be released in a future update?

**Comment by jackmcpickle** [comment]
Thanks @axelBrauneder - will look at this soon. Or feel free to create a PR. 😺

**Comment by HugoGiraudel** [comment]
Out of curiosity, what compiler is your IDE relying on?

**Comment by cmoleka** [comment]
node-sass and sass-loader successfully compiled with this suggestion.

**Comment by khashashin** [comment]
I've same behavior. PyCharm shows error: `invalid argument`. Also changed it as suggested by @axelBrauneder and it works without errors
