### ISSUE TITLE
Undefined mixin media

### ISSUE THREAD

**Issue by Trenbania** [eduardoboucas/include-media#192]
Not sure if this is a bug or my setup (probably the latter)!

I've installed a new WordPress theme that calls include-media on a test site so that I can play around and learn SASS. I'm using WP-SCSS to compile and it appears to be setup correctly.

However, I'm getting fatal errors:

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in /srv/.../wp-content/plugins/wp-scss/scssphp/src/Compiler.php on line 1328

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in /srv/.../wp-includes/class-wp-recovery-mode.php on line 169

These disappear if I remove _include-media.scss

If I uncomment line 539 for example:

@include media('>phone') { }

I then get undefined mixin media errors.

Is there anything in include-media.scss that I need to edit or should it work out of the box?

I have little knowledge of SASS and that probably shows!

**Comment by jackmcpickle** [comment]
Hi @Trenbania 

hard for us to help as using php to compile sass is not an ideal workflow. But sounds like you need to increase the php memory limit. 

If you're not comfortable with a CLI tool like gulp, webpack or even npm script, have a look around for Sass GUIs there are a few apps out there that give you a nice interface to compile the sass and then upload it to your WP site.
