### ISSUE TITLE
I made a library using this project, can I introduce it as a plugin?

### ISSUE THREAD

**Issue by black7375** [eduardoboucas/include-media#195]
- [Fluid-Size](https://github.com/black7375/Fluid-Size): Use **include-media** breakepoints to provide the `fit size` for the device.

If it doesn't get in the way, I want to put it in the plugin section.
Is it possible?

Thanks for reading.

**Comment by jackmcpickle** [comment]
Hi @black7375, 

thanks for you work. Feel free to make a pull request to update the readme and add your project to the list of plugins.

**Comment by black7375** [comment]
@jackmcpickle 
Thank you for your permission. :+1:

**Comment by black7375** [comment]
I'm glad you did the merge!!
