### ISSUE TITLE
include-media page on npm has a dodgy homepage field and link

### ISSUE THREAD

**Issue by revelt** [eduardoboucas/include-media#199]
the npm page https://www.npmjs.com/package/include-media shows "homepage"URL linking to http://include-media.com/ which seems a dodgy site:

<img width="421" alt="wrong-homepage" src="https://user-images.githubusercontent.com/8344688/92419066-20a59400-f163-11ea-8c80-a081cc4c7de4.png">

I checked the package's `package.json` https://github.com/eduardoboucas/include-media/blob/master/package.json#L18 — the "homepage" is set correctly.

Either something's wrong with your publishing automation scripts (contents somehow get amended during publishing) or we need to contact npm to clear the caches.

**Comment by jackmcpickle** [comment]
Its based on last published. As we haven't published a new version since 4 years ago it doesn't pull from Github with the updated url data.
