### ISSUE TITLE
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

### ISSUE THREAD

**Issue by sstikkel** [eduardoboucas/include-media#211]
I get a warning regarding line 443 $result: $result + map-get($numbers, $characters) / $digits;  Recommendation: math.div(map-get($numbers, $character), $digits) and @use "sass:math":

**Comment by codiejay** [comment]
hey @sstikkel please can i see your file setup? 
I can't even manage to setup my own project. 
i will appreciate any help | #212

**Comment by Supportic** [comment]
> I get a warning regarding line 443 $result: $result + map-get($numbers, $characters) / $digits; Recommendation: math.div(map-get($numbers, $character), $digits) and @use "sass:math":

This is because you are using a newer dart-sass version which encourages you to `@use "sass:math"` on top of the file and replace the division with math.div.

**Comment by alexanderalmstrom** [comment]
Any updates on this? We should really fix this to be able to use the latest sass version without getting those division warnings.

**Comment by jackmcpickle** [comment]
Yeah, might dedicate a day to this over the break. Thinking of a 2.0 release to fix the dart sass stuff and simply issues.

**Comment by jackmcpickle** [comment]
Note I've mainly switched to postcss, and i've written. https://www.npmjs.com/package/postcss-include-media

**Comment by alexanderalmstrom** [comment]
I've created a pull request here https://github.com/eduardoboucas/include-media/pull/214

**Comment by jackmcpickle** [comment]
resolved in 2.0 release https://github.com/eduardoboucas/include-media/pull/218
