### ISSUE TITLE
Release 2.0 on npm

### ISSUE THREAD

**Issue by jhildenbiddle** [eduardoboucas/include-media#216]
Are there any plans to publish the [2.0-release](https://github.com/eduardoboucas/include-media/tree/2.0-release) branch on npm? 

I realize I can install this GitHub branch as a dependency using npm as follows:

```bash
npm i -D eduardoboucas/include-media#2.0-release
```

The issue is that this approach locks the dependency to a specific GitHub branch rather than a semantic version available for packages published on npm which are required for update availability checks via automation or commands like `npm outdated`.

Thanks!

**Comment by jackmcpickle** [comment]
Good question. I was thinking about this the other day. @eduardoboucas what are your thoughts? Time to publish?

**Comment by kevinrodrigues** [comment]
Would also like to know please :)

**Comment by smarkey** [comment]
Would like to know too please 😃

**Comment by ashleynolan** [comment]
Would be great to get the v2 version published to NPM – we're currently using it for our CSS setup with @use and @forward and works with no issues. Even if it can be published and tagged as an alpha/beta release, that would be great so that we didn't have it tied to a github branch.

**Comment by Twikito** [comment]
Same thing here.
We use it at @ProtonMail and it would be great if we didn't have to rely on a specific GitHub branch instead of the latest released version.
Please consider publishing [2.0-release](https://github.com/eduardoboucas/include-media/tree/2.0-release) branch 🙏

**Comment by nico3333fr** [comment]
Yes, please please please 🙏

**Comment by jackmcpickle** [comment]
I would love to but only @eduardoboucas has the rights to publish.

**Comment by jackmcpickle** [comment]
While we wait for Ed - I did also publish a postcss version of include media a while back - As I mainly use css/postcss stack now. 

See https://www.npmjs.com/package/postcss-include-media

**Comment by eduardoboucas** [comment]
Sorry, I didn't realise I was a blocker here.

@jackmcpickle I tried to add you, but somehow that's not working 😢 

```sh
$ npm owner add jackmcpickle include-media

npm ERR! code EOWNERMUTATE
npm ERR! Failed to update package: "404 Not Found - PUT https://registry.npmjs.org/include-media/-rev/28-2068e1a6eba38bef23919fa92caad711 - Team not found"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eduardoboucas/.npm/_logs/2023-01-23T11_53_56_202Z-debug-0.log
```

In the meantime, can you confirm what exactly you want me to publish? Do I just checkout the `2.0-release` branch?

**Comment by jackmcpickle** [comment]
@eduardoboucas yes please publish the 2.0-release branch and then make it the default branch too or merge to main/master.

**Comment by Twikito** [comment]
@eduardoboucas nice to see you back!

Yes, the `2.0-release` branch uses sass modules, so it at least fixes quite a few warnings. 🙏

**Comment by eduardoboucas** [comment]
I have published version 2.0.0 from the `2.0-release` branch.

@jackmcpickle I've created https://github.com/eduardoboucas/include-media/pull/218, can you please review and merge?

**Comment by jackmcpickle** [comment]
Done. Thanks @eduardoboucas. 

I think we can offical close this issue now. :)

**Comment by Twikito** [comment]
Thanks a lot 🎉

**Comment by Twikito** [comment]
And could you create a release so that we could install the package via npm? 🙏

**Comment by jhildenbiddle** [comment]
Thank you!

**Comment by cmalven** [comment]
It would be nice to have this listed as an official release (with change notes) https://github.com/eduardoboucas/include-media/releases

It's a bit confusing right now that the releases end at 1.4.x, the listed tags end at 1.4.x, and yet the version on npm is 2.0

**Comment by jackmcpickle** [comment]
@cmalven published release now. Thanks for the reminder.
