### ISSUE TITLE
Compability with current sass version?

### ISSUE THREAD

**Issue by mwieth** [eduardoboucas/include-media#224]
Since the dart-sass package has been renamed to sass am I right assuming that the 2.0 version works with the current version of sass?

Thx in advance.

**Comment by jackmcpickle** [comment]
@mwieth correct. include-media@2 uses the canonical sass (dart-sass)

**Comment by ts-web** [comment]
I was confused by this, not knowing that `dart-sass` is the `sass` npm package. Can the readme be clarified?

**Comment by jackmcpickle** [comment]
No worries @ts-web - updated now. Hopefully thats clearer.
