### ISSUE TITLE
Error: Two forwarded modules both define a variable named $breakpoints

### ISSUE THREAD

**Issue by eballeste** [eduardoboucas/include-media#234]
I am trying to use include-media in a svelte 5/svelte-kit project and am able to get it to work when using @import rules but this comes with a bunch of console warnings related to the deprecation of @import in favor of @use. I had no idea this was a thing so now I'm trying to figure out how to get my previous scss starter files to work using @use and @forward. 

In my working setup I have a single `_head.scss` file that looks like this:

```scss
@import 'include-media/dist/include-media';

@import './fonts';
@import './variables'; // contains my version of $breakpoints
@import './mixins';
```

this is then parsed by sveltekit files using the following setup in my `svelte.config.js file`:
```javascript
export default {
	preprocess: sveltePreprocess({
		scss: {
			api: 'modern',
			//silenceDeprecations: ['import'],
			prependData: `@import 'src/styles/_head.scss';`
		},
	}),
}
```

this works great if i ignore all of the warnings, 
when i try to migrate this over to @use / @forward, i get the `$breakpoints` conflict error:

```scss
@forward 'include-media/dist/include-media';

@forward './fonts';
@forward './variables'; // Error: Two forwarded modules both define a variable named $breakpoints
@forward './mixins';
```
```javascript
export default {
	preprocess: sveltePreprocess({
		scss: {
			prependData: `@use 'src/styles/_head.scss' as *;`
		},
	}),
}
```

Does anybody know how to properly overwrite the $breakpoints variable when using @forward? Appreciate your time and help, thanks!

**Comment by eballeste** [comment]
I looked through the site/documentation, even the test files, and found no examples on how to setup a project with `include-media` and `@use`/`@forward`. the commit where `@use` was introduced to this library did not help me figure this out.

**Comment by jackmcpickle** [comment]
Hi @eballeste - yeah the new sass `@use` and `@forward` can get tricky. 

I spun up a new svelte 5 project and was able to get it working with this setup. 

```scss
// styles/vars.scss
$breakpoints: (
  'sm': 640px,
  'md': 768px,
  'lg': 1024px,
);
```

```svelte
<!-- +page.svelte -->
<style lang="scss">
    @use '../styles/vars';
    @use 'include-media/dist/include-media' with (
        $breakpoints: vars.$breakpoints
    );

    h1 {
        @include include-media.media('>sm') {
            color: red;
        }
        @include include-media.media('>md') {
            color: blue;
        }
    }
</style>
```
from what I could gather you have to pass the variable you want to override in a library now with the new `with ()` syntax. You cant pass the `$breakpoints` map directly into it. So you need to reference it with the `vars.$breakpoints` as its imported from the vars file.

Im sure there maybe other better ways of doing it but this was the easier method I could get working. 
[See repo](https://github.com/jackmcpickle/demo-sass-svelte)

**Comment by eballeste** [comment]
woof! amazing! thank you so much @jackmcpickle, i needed your example, and re-reading the sass documentation for `@forward` to help me find the solution to my problem. this is what my setup now looks like and it works perfectly:
```scss
// _head.scss
@forward './fonts';
@forward './variables' hide $breakpoints;

@use './variables';

@forward 'include-media/dist/include-media' with (
    $breakpoints: variables.$breakpoints
);
```

```javascript
// svelte.config.js
export default {
	...
	preprocess: sveltePreprocess({
		scss: {
			prependData: `@use 'src/styles/_head.scss' as *;`
		},
	}),
	...
}
```
 
 ```html
 <!-- page.svelte -->
 <style lang="scss">
    h1 {
        color: $color-black;

        @include media('>=md') {
            color: pink;
        }
    }
</style>
 ```
 
 with this i avoid the boilerplate in each component and i also don't need to namespace my `@include media()` rules.
 again, thank you so much!

**Comment by jackmcpickle** [comment]
Nice one! Yeah its a tricky one. Glad to have helped.
