### ISSUE TITLE
Unknown unit 'phone' or any other sass variable I try

### ISSUE THREAD

**Issue by kjs3** [eduardoboucas/include-media#30]
I'm getting "Unknown unit x" anytime I try to pass a sass var (phone, tablet, etc.) to the media mixin.

This is literally all my sass:

```
@import "include-media";

@include media(">phone") {
  body {
    background-color: red;
  }
}
```

and here's the output I get when compiling:

```
WARNING: Unknown unit `phone`.
	on line 342 of bower_components/include-media/dist/_include-media.scss
	from line 314 of bower_components/include-media/dist/_include-media.scss
	from line 222 of bower_components/include-media/dist/_include-media.scss
	from line 112 of bower_components/include-media/dist/_include-media.scss
	from line 29 of stdin
```

If I pass a px value it works fine.

Any idea what's going on here?

This is using node-sass 3.0.0-beta.4 which uses libsass 3.2.0-beta.2

**Comment by sevenupcan** [comment]
I think I'm having a similar issue. This is the error I get

    $number: false is not a number for 'unit' on line 227 of include_media.scss

**Comment by eduardoboucas** [comment]
Are you still experiencing these issues?

**Comment by HugoGiraudel** [comment]
Ping @kjs3 and @sevenupcan: is this still happening on your side after you updated the lib? :)

**Comment by HugoGiraudel** [comment]
It's been 2 months. Shall we close?

**Comment by eduardoboucas** [comment]
Closing. @kjs3 and @sevenupcan, please give us a shout if you're still experiencing this problem.

**Comment by kjs3** [comment]
Sorry, I finally got around to reevaluating this and it's all good now.
Thanks.
