### ISSUE TITLE
Rename mixin to avoid naming conflicts with other libraries

### ISSUE THREAD

**Issue by stacyk** [eduardoboucas/include-media#32]
We use Bourbon Neat and they have a mixin called media http://thoughtbot.github.io/neat-docs/latest/#media

Wondering if this will likely cause problems down the road. Just throwing it out there.

**Comment by eduardoboucas** [comment]
This one is a bit difficult because we would be completely breaking compatibility with previous versions which is something I really don't want to do.

Also, we'd have to change the name of the library because you wouldn't be including "media" anymore, right? :)

**Comment by stacyk** [comment]
I figured it was probably not doable, but it doesn't hurt to ask :)

**Comment by eduardoboucas** [comment]
But thanks for raising the issue! I'm sure more people are using both include-media and Bourbon and had the same thoughts.

**Comment by eduardoboucas** [comment]
I've reopened this because this was raised again, this time by @re6exp.

I appreciate this is a problem when using other libraries, such as Bourbon, but we have to find a way to address this without breaking compatibility with previous versions.

Any ideas?

**Comment by joseluis** [comment]
Defining mixins with the same name effectively overrides the previous definition. So the order of inclusion of the libraries is important. If you want to avoid mixin overriding, your library should be the last one included.


But, in anycase I can only think of this small improvement:


1. rename your media mixin to a more unique name like include-media
2. check if the media mixin is already defined by another library
3. if not (as long as you don't want to override the other mixin), create an alias named media.

```
@mixin include-media($args) {
  // stuff
}

@if mixin-exists(media) {
}
@else {
  @mixin media($args...) {
    @include include-media($args...)
  }
}
```

This way you can mantain the same backwards compatibility as before. (optionally, only when there are no collisions). And the media mixin will stop working if it's overriden by another library loaded after, same as before.

But now we would have a unique mixin name that wont conflict with other libraries and will always work.

**Comment by eduardoboucas** [comment]
That's exactly what I was thinking, @joseluis. 

I see that `mixin-exists()` is supported in RubySass 3.3+ and all versions of LibSass (according to [Sass Compatibility](http://sass-compatibility.github.io/#feature_detection_functions)), so we would be ruling out people on RubySass 3.2.

@HugoGiraudel it'd be great to hear your thoughts on this.

**Comment by HugoGiraudel** [comment]
> Mixins may not be defined within control directives or other mixins.

**Comment by HugoGiraudel** [comment]
Namespace your mixin and bump major version.

**Comment by prisis** [comment]
Or just import "include-media"; after neat and bourbon, like i did [look](https://github.com/growcss/growcss/blob/master/src/scss/growcss.scss)

**Comment by eduardoboucas** [comment]
@prisis That's the easiest workaround, yes. 

I don't know when we'll get to revisit this again, but I'm personally not a fan of renaming the mixin at all. The whole library is built on the premise of a simple and natural syntax, and that was the motivation behind every new feature since the first release. Going from `@include media()` to `@include im-media()' or similar seems like a step backwards.

It would solve a problem (or make things easier) for some people, but breaking compatibility with everything we've done so far seems too big of a price to pay. Also, it's not like we're breaking good practices when compared to other libraries — Sass has a global namespace and people are aware of it, I don't think it's up to us to solve that issue (even though we could in this case).

I'll let @HugoGiraudel and others speak their mind about this.

**Comment by stacyk** [comment]
It was giving me problems when I tried that but maybe I will give it another try.

**Comment by HugoGiraudel** [comment]
I'd like to do this:

```scss
@mixin im-media($conditions...) { 
  // ...
}

@mixin media($conditions...) {
  @include im-media($conditions...) {
    @content;
  }
}
```

If a lib overwrites `media(..)`, the user can still use `im-media(..)`. Else, it's as usual.

**Comment by eduardoboucas** [comment]
That makes sense. My only problem with that is that import order will still matter. If you import include-media after Bourbon, it will still overwrite Bourbon's `media()` mixin. Isn't that solving just a fraction of the problem? Or worse, won't it give the impression that things will just work fine together, when it's not the case? I think users should be aware that import order matters and there's really no way around it.

**Comment by HugoGiraudel** [comment]
That makes sense I suppose. Not sure how to deal with this then. I'd love external opinions from experienced people ideally. 

Ping @ericam, @chriseppstein, @scottkellum. If you feel like giving your 2 cents, that would be very appreciated. :)

**Comment by eduardoboucas** [comment]
On the other hand, your solution will mean that **if users are aware of this limitation** and deliberately choose to import Bourbon after include-media, they will be able to use the mixins from both libraries, which doesn't happen at the moment. I'm torn.

**Comment by scottkellum** [comment]
Yeah, general rule is to import smaller more specific libs like this one after larger ones like Bourbon. There are going to be conflicts and it’s probably not a good idea to use all the things from all the libraries at once. If it were me I’d probably close without change. Unsure why you would want to have two different media query mixins in your project.

**Comment by eduardoboucas** [comment]
I agree.

**Comment by ericam** [comment]
Yep. We do some more complex name-wrangling in Susy, just because we don't *want* to provide media-queries — so we do everything we can to get out of the way, and integrate with other plugins. That's not the case here. I'd leave it as-is, but note the potential conflict (and solution) in your docs.

**Comment by eduardoboucas** [comment]
@scottkellum @ericam thanks for your insights!

@HugoGiraudel what do you reckon? Should we close this?

**Comment by HugoGiraudel** [comment]
Thank you all for your input on the matter. This is a no go, we are closing.

**Comment by gilbox** [comment]
It's really a shame. `include-media` and bourbon neat work nicely together except for this conflict. For that to work you have to use `@include media` from both libraries. Any chance of including an additional mixin that does the same thing under a different name?

**Comment by HugoGiraudel** [comment]
> I want to use @include media from both libraries.

That sounds like a terrible idea to me. There is no reason to handle multiple breakpoint managers, and the multiplication of dependencies is generally considered a bad practice.

**Comment by gilbox** [comment]
One is for managing breakpoints, the other is for columns. 

> the multiplication of dependencies is generally considered a bad practice

Not sure what you mean by that.

**Comment by prisis** [comment]
Just include Bourbon than Neat and last include-media... it works for me

Or make you one alias for it, 

Create a new file alias.scss

Include all helpers from include-media and the config.scss on the top, than you need only copy the mixin from media.scss and rename it...

**Comment by gilbox** [comment]
Thanks @prisis, I'm not convinced that's actually a better solution. If include-media had some central file (not `_media.scss`) that did `@imports` it would be ok, but as it is, your suggestion makes for confusing upgrades.

**Comment by chriseppstein** [comment]
FWIW, We view this kind of conflict as a failure of Sass's language. Sass 4.0 will make it possible for library consumers to manage conflicts like these on their own. Until then, we suggest that libraries provide prefixed versions of contentious mixin names. E.g. `bourbon-media` so that it is possible to avoid the collision by what is imported. Note: Some imports can de-prefix the prefixed version as long as there's a way avoid that import.

`

**Comment by eduardoboucas** [comment]
That makes sense.

In the meantime, a possible solution would be to have a separate dist file with the prefixed mixin. That way regular users would carry on using the library without any compatibility problems, and those that need to use it in conjunction with other libraries with naming conflicts (such as Bourbon), could simply grab the prefixed include-media dist file instead.

It would be quite simple to integrate this into our Gulp workflow. It's not pretty, but it's the only thing I can think of to make everyone happy. What do you think @HugoGiraudel?

**Comment by HugoGiraudel** [comment]
Meh.. I guess so.

**Comment by eduardoboucas** [comment]
@gilbox would you find that useful?

**Comment by gilbox** [comment]
Thanks @eduardoboucas it would be useful. I gave it [a go](https://github.com/eduardoboucas/include-media/pull/95/files)

**Comment by scottkellum** [comment]
Good reference on jQuery lib conflict settings: https://api.jquery.com/jquery.noconflict/
