### ISSUE TITLE
Name conflicts with bourbon.

### ISSUE THREAD

**Issue by re6exp** [eduardoboucas/include-media#33]
The 'media' mixin conflicts with Bourbon Neat mixin with the same name.
Would you prepend to all of include-media mixins/variables/maps some prefix, e.g. smth like 'eb-' or 'im-'?
It could resolve any possible naming conflicts in the future, until we'll get possibility to rename compilation unit in sass. But [appropriate task](https://github.com/sass/sass/issues/353) status at sass/sass is steel 'open', since 2012... :(

**Comment by eduardoboucas** [comment]
I'll move the discussion to [#32](https://github.com/eduardoboucas/include-media/issues/32), if that's alright. Thanks!
