### ISSUE TITLE
v1.2 does not install via bower

### ISSUE THREAD

**Issue by JoeCianflone** [eduardoboucas/include-media#38]
Hi,

I've run this several times and I'm not getting version 1.2 to install.  I checked what bower installed too, just to be sure and it is indeed installing 1.1.2 and not 1.2.  Just to be sure, I also removed the package from my `bower.json` file and ran `bower prune && bower cache clean` so I'm pretty certain this isn't a cache issue. 

![screen shot 2015-05-30 at 12 38 57 pm](https://cloud.githubusercontent.com/assets/989648/7898276/34121a0c-06c9-11e5-8215-7a8e5af53ee3.png)

**Comment by HugoGiraudel** [comment]
@JoeCianflone Can you try with 1.3? :)

**Comment by eduardoboucas** [comment]
I just tested with 1.3 and it worked. Let me know if you're still experiencing this.

**Comment by JoeCianflone** [comment]
Worked perfectly for 1.3.  Thanks guys!

**Comment by HugoGiraudel** [comment]
Yay. :)
