### ISSUE TITLE
Automate build process

### ISSUE THREAD

**Issue by eduardoboucas** [eduardoboucas/include-media#54]
Couple of ideas:

- [x] Add a pre-commit hook to:
  * Run the tests
  * Run the linter
- [x] Add a Gulp `build` task
  * Update the dist
  * Update SassDoc

**Comment by HugoGiraudel** [comment]
> Automatically compile the source when something is added to master and push the new dist file back to the repo if tests succeed

We only need to set up a Git hook to run the `default` task from Gulp. This task will run `test`, then if everything went fine, `concat`, then if everything went fine, it'll push to `master`.

**Comment by eduardoboucas** [comment]
I've been looking at this and I wonder if the `bower.json` part makes sense, because we would need to have a template version of the file (with the @version@ placeholder) and a dist version as well, with the version replaced. Maybe it's too much hassle for what it is.

**Comment by HugoGiraudel** [comment]
> because we would need to have a template version of the file (with the @version@ placeholder) and a dist version as well, with the version replaced. Maybe it's too much hassle for what it is.

True.

**Comment by HugoGiraudel** [comment]
Drafting something with [gh-pages](https://github.com/tschaub/gh-pages):

```javascript
gulp.task('deploy', ['build', 'sassdoc'], function () {
  gh.publish(path.join(__dirname, 'sassdoc'), {
    add: true,
    message: 'Updated SassDoc'
  }, function (err) { 
    if (err) console.log(err);
  });
});
```
