### ISSUE TITLE
Consider using SassDoc

### ISSUE THREAD

**Issue by HugoGiraudel** [eduardoboucas/include-media#6]
For documentation. :)

**Comment by eduardoboucas** [comment]
Do you think it makes sense for something this size? The only public feature is the mixin. Would you also include "private" functions/helpers?

**Comment by HugoGiraudel** [comment]
Depends on what you expect from users. If they can build upon your lib, then document everything. :)

**Comment by eduardoboucas** [comment]
Done! SassDoc [here](http://eduardoboucas.com/include-media/doc/)

**Comment by HugoGiraudel** [comment]
Why isn't the config documented?

**Comment by eduardoboucas** [comment]
Good point. I'll have another look at SassDoc to see what are the best annotations to document lists. 

I've reopened this. Cheers Hugo!

**Comment by eduardoboucas** [comment]
Fixed in [#22](https://github.com/eduardoboucas/include-media/pull/22) and [#23](https://github.com/eduardoboucas/include-media/pull/23).
