### ISSUE TITLE
Slightly increase line-height

### ISSUE THREAD

**Issue by HugoGiraudel** [eduardoboucas/include-media#67]

**Comment by HugoGiraudel** [comment]
What do you think @eduardoboucas?

**Comment by eduardoboucas** [comment]
I've been playing with this the other day. I think that I wouldn't increase it more than 1px, to be honest. This is how it would look:

![screen shot 2015-06-07 at 22 55 48](https://cloud.githubusercontent.com/assets/4162329/8026299/6ee53678-0d68-11e5-995f-d01b12acbfe8.png)

That feels enough for me. What do you reckon?

**Comment by HugoGiraudel** [comment]
I trust your judgement. :)
