### ISSUE TITLE
sass doesn't compile when using media query ranges

### ISSUE THREAD

**Issue by m-i-k-e** [eduardoboucas/include-media#74]
I'm using grunt to compile my sass on a 10.10.3 iMac.

These statements cause grunt to eat all the available memory, and lock the machine (eventually):
 
@include media (">tablet" , "<desktop") { ... }

These are my breakpoints:
$breakpoints: (
        'phone': 320px,
        'tablet': 768px,
        'desktop': 1024px
) !default;

**Comment by eduardoboucas** [comment]
How old is your `_include-media.scss` file? If it's not recent, can you try with the latest version?

**Comment by HugoGiraudel** [comment]
This is likely to be a duplicate of #37.

**Comment by m-i-k-e** [comment]
I've upgraded and it's fixed. Thanks!

**Comment by HugoGiraudel** [comment]
You'll have to upgrade again in a couple of minutes. @eduardoboucas will update the dist file to 1.3 soon enough.
