### ISSUE TITLE
Throws $number` of `unit($number)` must be a number with gulp-sass

### ISSUE THREAD

**Issue by arkroy** [eduardoboucas/include-media#78]
Trying to use it with Foundation 5 grids. While it works on codepen and sassmeister it throws the following error when compiling with gulp-sass. Am I doing something wrong? Would appreciate it if you could help.

gulp-sass] argument `$number` of `unit($number)` must be a number
Backtrace:
	src/scss/quarks/_responsive.scss:226, in function `unit`
	src/scss/quarks/_responsive.scss:226, in function `get-expression-value`
	src/scss/quarks/_responsive.scss:264, in function `parse-expression`
	src/scss/quarks/_responsive.scss:447, in mixin `media`
	src/scss/quarks/_responsive.scss:449, in mixin `media`
	src/scss/quarks/_responsive.scss:660 on line 226

**Comment by HugoGiraudel** [comment]
Could you show us how you use it? Without a code snippet, it is going to be hard to help unfortunately. :(

**Comment by arkroy** [comment]
It outputs the classes for creating a grid onto the compiled CSS (ref screenshot attached). Sorry about the code... thought it might be useful.
![screen shot 2015-06-12 at 12 40 21 am](https://cloud.githubusercontent.com/assets/1106841/8115732/0465f8c4-109b-11e5-8a8c-e007852d1f12.png)

**Comment by HugoGiraudel** [comment]
Please, share the lin to the SassMeister. :)

**Comment by arkroy** [comment]
Thanks for the quick response. http://sassmeister.com/gist/c605838e5277469cdebb

**Comment by HugoGiraudel** [comment]
Could you narrow the problem down? Like find the `media(..)` include that actually triggers the issue on your side?

**Comment by arkroy** [comment]
That would be line 656 from the gist-       
@include media ("screen", ">medium") {
      @include grid-classes($size:m);

**Comment by HugoGiraudel** [comment]
Could you remove all things from Foundation and try to compile using this media include?

**Comment by arkroy** [comment]
Works.  http://sassmeister.com/gist/6053a315109942d81f68

I guess it isn't related to include media.
Thanks for your help.

**Comment by HugoGiraudel** [comment]
No problem. :)

**Comment by arkroy** [comment]
If I may ask (in this ticket) is there a way to generate the media queries with em/rem values while using px for $breakpoints. Tried using a em and a rem calculator function but doesn't work. Any ideas??

**Comment by HugoGiraudel** [comment]
Define them as em/rem in the `$breakpoints` map.

**Comment by arkroy** [comment]
Thanks :)

**Comment by HugoGiraudel** [comment]
No problem!
