### ISSUE TITLE
Provide option for no media queries

### ISSUE THREAD

**Issue by gunnx** [eduardoboucas/include-media#82]
Add option like 'Breakpoint' that allows you to switch off media queries with a variable

**Comment by eduardoboucas** [comment]
@gunnx we're discussing the best way to tackle this, please bare with us. :)

**Comment by gunnx** [comment]
@eduardoboucas thanks, its a great plugin and I really like the syntax so hopefully you can resolve this one easily :)

**Comment by eduardoboucas** [comment]
:+1:

**Comment by eduardoboucas** [comment]
Added in #83. More info [here](http://include-media.com/documentation/#variable-im-media-support).
