### ISSUE TITLE
problem resolution queries 

### ISSUE THREAD

**Issue by Nirazul** [eduardoboucas/include-media#90]
I can't get to work following resolution query with your latest version:
`res2x: ('(-webkit-min-device-pixel-ratio: 2)', '(min-resolution: 192dpi)', '(min-resolution: 2.0dppx)')`

The output is always the first one in the list (at least I'm thinking this is the pattern):
```
  @media (-webkit-min-device-pixel-ratio: 2) {...}
```

**Comment by HugoGiraudel** [comment]
Could you please try:

``scss
'(-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi), (min-resolution: 2.0dppx)'
```

**Comment by Nirazul** [comment]
Thanks for the quick help :)
You suggestion works, but as a strange side effect I get this output now:
```
@media (-webkit-min-device-pixel-ratio: 3), (-webkit-min-device-pixel-ratio: 3.6458333333333335), (min-resolution: 350dpi), (min-resolution: 3dppx) {...}
```

**Comment by HugoGiraudel** [comment]
Wow. We'll run some tests.

**Comment by eduardoboucas** [comment]
@Nirazul this is using LibSass, correct?

**Comment by Nirazul** [comment]
correct!

I'll get the versions...

**Comment by HugoGiraudel** [comment]
* What version of include-media are you using?
* How did you install it?
* Did you modify it?
* What code do you try to run?

**Comment by Nirazul** [comment]
- What version of include-media are you using?
  - [this one](https://raw.githubusercontent.com/eduardoboucas/include-media/master/dist/_include-media.scss)
- How did you install it?
  - I copy-pasted the file
- Did you modify it?
  - At begin yes, but as I ran into problems, I reverted to unmodified
- What code do you try to run?
  - I stripped it down to just running gulp-sass:
    ` .pipe( sass().on('error', function() {}) ) `

**Comment by HugoGiraudel** [comment]
> I stripped it down to just running gulp-sass: .pipe( sass().on('error', function() {}) )

So you are simply trying to compile the dist file? Do you have any code of yours?

**Comment by Nirazul** [comment]
I'm sorry, I updated my gulpfile again. Apparently autoprefixer did some strange 'optimisations'...

However, this syntax still does not work. Is it deprecated?
```
  'retina2x': (
    '(-webkit-min-device-pixel-ratio: 2)',
    '(min-resolution: 192dpi)'
  ),
```

In any case, thanks for the help! :)

**Comment by HugoGiraudel** [comment]
With LibSass, the list notation is buggy. We are aware about this and unfortunately could not find a decent work-around. In RubySass, it doesn't matter whether it's written as a list or a string, but in LibSass it needs to be a single string.

**Comment by Nirazul** [comment]
Thanks for clearing things up. And thanks again for the great work on this module, it's the best I've found so far when it comes to handling media queries in sass.

**Comment by eduardoboucas** [comment]
We'll favour the string notation and flag this issue. Thanks for reporting it.

**Comment by Nirazul** [comment]
To anyone who's coming to this thread after me:

If you have problems with resolution queries and autoprefixer, just get out of the way of autoprefixer and use: `myResolution: '(min-resolution: 2dppx)' `
It will be expanded for you to dpi and webkit min/max device pixel ratios.
